### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by kubilaycaglayan** [kubilaycaglayan/weather-app#3]
Hello Team,

Please, feel free to note your feedback down after my presentation.

With all my respect...

**Comment by kubilaycaglayan** [comment]
A thunderstorm symbol should be added.
:cloud_with_lightning:

**Comment by mariosknl** [comment]
That was a really well-structured project. Well done Kubilay. I liked the animation and the input functionality as well.

**Comment by frankopkusianwar** [comment]
Well done kubilay

**Comment by teekaytech** [comment]
Nice one, Kubilay. As a suggestion, you should be wary of how you use white spaces. Most times it makes your code look legible but sometimes, it might be unnecessary.

Again, It's a nice project. With these wonderful features, I'm so curious about JavaScript now than ever :smile:

**Comment by kubilaycaglayan** [comment]
Thank you very much for your notices.
@teekaytech, I will be careful about that.
👋
