### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by kubilaycaglayan** [kubilaycaglayan/weather-app#4]
Thanks for listening to my presentation :wave:

Please drop your valuable comments below ⏬

**Comment by mariosknl** [comment]
Thanks for the presentation Kubilay. Today's meeting was great and I really like the refactoring session on your project.

**Comment by teekaytech** [comment]
Yeah. The refactoring session was so interactive and educational. Thanks for the presentation.
